### PR TITLE
Fix error in querySourceRaw

### PR DESCRIPTION
**Pull request by gmixo**
Fix error in querySourceRaw with getAttribute('type')
el.getAttribute("type"), el.getAttribute('contenteditable') doesn't work
for type maybe more correct is check el.tagName because not all tags return correctly their types,
type attribute actually some strange for me but **el.type** works for **fieldset, radio, checkbox** and **date**

### CODE REVIEW

**Comment by gmixo** [comment]
Hmm.. I just want to add my fix, not 8 commits. How they got here?

**Comment by 5HT** [comment]
Our bad after series of reverts. Are you tested your changes on all browsers. IIRC el.type was failing on some, that is why I put it in that way.

**Comment by gmixo** [comment]
Actually not all.. so I better use tagName for check
**element.contentEditable** represented on w3schools site and it seems ok

**Comment by gmixo** [comment]
Ok it's seriously than I think - tagName no good idea 
need more tests for el.type

**Comment by 5HT** [comment]
Can I close this issue due to error in commits?

**Comment by gmixo** [comment]
well current solution isn't correct and my fix is more preferable, in case of fieldset and for contentEditable property
for date checkbox and radio maybe there is no difference, since getAttribute works only with tag attributes
currently no complex solution for determine type of input element so maybe we should use both approaches, detect tag at first, and detect type for input

**Pull request merged**
